msg() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    GREEN="${BOLD}\e[1;32m"
	local mesg=$1; shift
	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
}
post_install() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  if [[ -z $2 ]]; then
      msg "YOU DO NEED TO INSTALL ONE OF THE OPT DEPENDS FOR YOUR VIDEO CARD"
  fi
}

post_upgrade() {
  post_install $1 $2
}

post_remove() {
  post_install $1 removing
}

