#! /bin/bash
TEXTDOMAINDIR=/usr/share/locale
TEXTDOMAIN=pacman-gui

# path pacman-script.sh
path=/usr/share/pacman-gui

export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=pacman-gui

pkexec "$path/pacman-gui.sh" "$@"
